# Generated by Django 5.2.9 on 2025-12-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event or venue title (sanitized)', max_length=500)),
                ('start_date', models.DateTimeField(blank=True, help_text='Event start date/time. Null if not available from source.', null=True)),
                ('venue_name', models.CharField(blank=True, help_text='Name of the venue hosting the event', max_length=500)),
                ('city', models.CharField(db_index=True, help_text='Standardized city name (Johannesburg or Pretoria)', max_length=100)),
                ('category', models.CharField(blank=True, help_text='Event category derived from Google Places types', max_length=200)),
                ('event_url', models.URLField(blank=True, help_text='URL to the event or venue page', max_length=2048)),
                ('source', models.CharField(default='google_places', help_text='Data source identifier (e.g., google_places, apify)', max_length=100)),
                ('raw_payload', models.JSONField(default=dict, help_text='Complete raw API response for data lineage')),
                ('source_id', models.CharField(help_text='Unique identifier from the source (e.g., Google Place ID)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Event or venue description (sanitized)')),
                ('address', models.CharField(blank=True, help_text='Full address of the venue', max_length=500)),
                ('latitude', models.FloatField(blank=True, help_text='Venue latitude coordinate', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Venue longitude coordinate', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['city', 'start_date'], name='events_even_city_662f49_idx'), models.Index(fields=['category'], name='events_even_categor_aca11d_idx'), models.Index(fields=['source'], name='events_even_source_bc4f5a_idx'), models.Index(fields=['created_at'], name='events_even_created_52c227_idx')],
            },
        ),
    ]
