# Generated by Django 5.2.9 on 2025-12-17 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_image_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated conversation title",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this conversation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Conversation",
                "verbose_name_plural": "Chat Conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        help_text="Message role (user, assistant, system)",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Message content")),
                (
                    "tokens_used",
                    models.IntegerField(
                        default=0, help_text="Number of tokens used for this message"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="Conversation this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="events.chatconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserTokenUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        default=0,
                        help_text="Total tokens used (resets monthly or on reset)",
                    ),
                ),
                (
                    "last_reset",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When token usage was last reset"
                    ),
                ),
                (
                    "monthly_limit",
                    models.IntegerField(
                        default=10000, help_text="Monthly token limit per user"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User whose token usage is tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Token Usage",
                "verbose_name_plural": "User Token Usage",
            },
        ),
    ]
